/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CommunityScreen` | `/CommunityScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EarningsScreen` | `/EarningsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HealthScreen` | `/HealthScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LearnScreen` | `/LearnScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SafetyScreen` | `/SafetyScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/ChatbotAssistant`; params?: Router.UnknownInputParams; } | { pathname: `/components/NeoBrutalismCard`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CommunityScreen` | `/CommunityScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/EarningsScreen` | `/EarningsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/HealthScreen` | `/HealthScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/LearnScreen` | `/LearnScreen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/SafetyScreen` | `/SafetyScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ChatbotAssistant`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NeoBrutalismCard`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CommunityScreen${`?${string}` | `#${string}` | ''}` | `/CommunityScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/EarningsScreen${`?${string}` | `#${string}` | ''}` | `/EarningsScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/HealthScreen${`?${string}` | `#${string}` | ''}` | `/HealthScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/LearnScreen${`?${string}` | `#${string}` | ''}` | `/LearnScreen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/SafetyScreen${`?${string}` | `#${string}` | ''}` | `/SafetyScreen${`?${string}` | `#${string}` | ''}` | `/components/ChatbotAssistant${`?${string}` | `#${string}` | ''}` | `/components/NeoBrutalismCard${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CommunityScreen` | `/CommunityScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/EarningsScreen` | `/EarningsScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/HealthScreen` | `/HealthScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/LearnScreen` | `/LearnScreen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/SafetyScreen` | `/SafetyScreen`; params?: Router.UnknownInputParams; } | { pathname: `/components/ChatbotAssistant`; params?: Router.UnknownInputParams; } | { pathname: `/components/NeoBrutalismCard`; params?: Router.UnknownInputParams; };
    }
  }
}
